# Generated by Django 3.0.2 on 2022-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рубрики')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'ProductRubric',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('author', models.CharField(max_length=255, verbose_name='ФИО автора')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='product_img/', verbose_name='Картинка товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField()),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес товара')),
                ('count_of_product', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во товара на складе')),
                ('rubric', models.ManyToManyField(related_name='product', to='catalog.ProductRubric')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
