# Generated by Django 3.0.2 on 2022-06-24 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EProduct',
            new_name='DigitalProduct',
        ),
        migrations.RenameModel(
            old_name='PProduct',
            new_name='MaterialProduct',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
        migrations.AlterModelTable(
            name='digitalproduct',
            table='DigitalProduct',
        ),
        migrations.AlterModelTable(
            name='materialproduct',
            table='MaterialProduct',
        ),
        migrations.AlterModelTable(
            name='productreview',
            table='ProductReview',
        ),
    ]
