# Generated by Django 3.0.2 on 2022-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220625_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='catalog.ProductType'),
        ),
    ]
