# Generated by Django 3.0.2 on 2022-06-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220624_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип товара'),
        ),
    ]
