# Generated by Django 3.0.2 on 2022-06-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220625_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.ManyToManyField(blank=True, default='type_of_product', null=True, to='catalog.ProductType'),
        ),
    ]
