# Generated by Django 3.0.2 on 2022-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220628_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.ManyToManyField(blank=True, default='type_of_product', to='catalog.ProductType'),
        ),
    ]
