# Generated by Django 3.0.2 on 2022-07-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220713_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupun',
            new_name='coupon',
        ),
    ]
